### ISSUE TITLE
For some reason it changes/deletes the user/root passwords whenever it finishes. 

### ISSUE THREAD

**Issue by sundenlast** [expo1337/dwm_dotfiles#1] opened 2024-04-28 22:14 UTC
Title. There's not much else I can say, I run the script exactly as intended and when it finishes I can't login lol. It tells me it's the wrong password.
I noticed that in the video after you run ./install.sh it asks you for the sudo/root password, I don't know if it's outdated or if I'm doing something wrong, but in my case it doesn't. Maybe that's related, can't really say for sure.

**Comment by RobinHirst11** [comment] 2024-06-09 23:55
Worked perfectly fine for me, might be a you issue

**Comment by BigBoyDriver** [comment] 2024-08-12 15:13
yeah it changed the root password for me too
i really dont want to reinstall arch

**Comment by expo1337** [comment] 2024-11-08 23:37
The issue was caused by a package name change in the arch repositories which made the package install phase fail. This caused the zsh installation to fail which means that you were stuck on a shell that was not installed. Should be fixed now

**Closed as completed by expo1337** 2024-11-08 23:37 UTC
